server:
  port: 6200

eureka:
  client:
    serviceUrl:
      defaultZone: http://root_fuji:1234@localhost:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/CATEGORY-DB-TEST

  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: http://localhost:8080/realms/quiz-tech
          jwk-set-url: ${spring.security.oauth2.resourceServer.jwt.issuer-uri}/protocol/openid-connect/certs