server:
  port: 6100

  tomcat:
    max-http-post-size: 10485760
    max-http-patch-siz: 10485760

eureka:
  client:
    serviceUrl:
      defaultZone: http://root_fuji:1234@localhost:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/CATEGORY-QUIZ-DB

  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: http://localhost:8080/realms/quiz-tech
          jwk-set-url: ${spring.security.oauth2.resourceServer.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: quiz-front
      principal-attribute: preferred_username

other:
  service:
    url:
      quiz-url-get: http://localhost:6110/api/quiz/get
      quiz-url-category: http://localhost:6110/api/quiz/getByCategory

image:
  storage:
    local:
      directory: E:\PROJECT\exam-quiz\front-quiz\src\assets