server:
  port: 6100

eureka:
  client:
    serviceUrl:
      defaultZone: http://root_fuji:1234@localhost:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CATEGORY-QUIZ-DB
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
    show_sql: true

  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: http://localhost:8080/realms/quiz-tech
          jwk-set-url: ${spring.security.oauth2.resourceServer.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: quiz-front
      principal-attribute: preferred_name

other:
  service:
    url:
      quiz: http://localhost:6110/api/quiz/get