server:
  port: 6200

eureka:
  client:
    serviceUrl:
      defaultZone: http://root_fuji:1234@localhost:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/CATEGORY-DB-TEST

  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/quiz-tech}
          jwk-set-url: ${KEYCLOAK_KEY_URL:http://localhost:8080/realms/quiz-tech/protocol/openid-connect/certs}