server:
  port: 6100

  tomcat:
    max-http-post-size: 10485760
    max-http-patch-size: 10485760

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://root_fuji:1234@localhost:8761/eureka}

spring:
  data:
    mongodb:
      uri: mongodb://mongodb-category:27018/CATEGORY-DB

  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/quiz-tech}
          #jwk-set-url: ${KEYCLOAK_KEY_URL:http://localhost:8080/protocol/openid-connect/certs}

jwt:
  auth:
    converter:
      resource-id: quiz-front
      principal-attribute: preferred_username

other:
  service:
    url:
      quiz-url-get: http://localhost:6110/api/quiz/get
      quiz-url-category: http://localhost:6110/api/quiz/getByCategory

image:
  storage:
    local:
      directory: /home/PROJECT