server:
  port: 8200

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://root_fuji:1234@localhost:8761/eureka

spring:
  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: http://localhost:8080/realms/quiz-tech
          jwk-set-url: ${spring.security.oauth2.resourceServer.jwt.issuer-uri}/protocol/openid-connect/certs


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      globalCors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200/**"
            allowedHeaders: "*"
            allowedMethods: "*"

      routes:
        - id: category
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/category/**
        - id: quiz
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/api/quiz/**
        - id: question-service
          uri: lb://QUESTION-SERVICE
          predicates:
            - Path= /api/question/**
        - id: result-quiz-service
          uri: lb://RESULT-QUIZ-SERVICE
          predicates:
            - Path= /api/result/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**




