server:
  port: 6110

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://root_fuji:1234@localhost:8761/eureka}

spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:QUIZ-DB}
      #username: ${SPRING_DATA_MONGODB_USERNAME:ixml}
      #password: ${SPRING_DATA_MONGODB_PASSWORD:1234}

  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/quiz-tech}
          #jwk-set-url: ${KEYCLOAK_KEY_URL:http://localhost:9090/realms/quiz-tech/protocol/openid-connect/certs}

jwt:
  auth:
    converter:
      resource-id: quiz-front
      principal-attribute: preferred_username

other:
  service:
    url:
      category-url-get: http://localhost:6100/api/category/get
      category-url-patch: http://localhost:6100/api/category/addQuiz
      question-url-byQuiz: http://localhost:6120/api/question/byQuiz

image:
  storage:
    local:
      directory: /home/PROJECT