server:
  port: 6110

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://root_fuji:1234@localhost:8761/eureka}

spring:
  data:
    mongodb:
      uri: ${MONGO_DB_QUIZ_URL:mongodb://ixml:1234@quiz-mongodb:27017/QUIZ-DB}

  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/quiz-tech}
          jwk-set-url: ${spring.security.oauth2.resourceServer.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: quiz-front
      principal-attribute: preferred_username

other:
  service:
    url:
      category-url-get: http://localhost:6100/api/category/get
      category-url-patch: http://localhost:6100/api/category/addQuiz
      question-url-byQuiz: http://localhost:6120/api/question/byQuiz

image:
  storage:
    local:
      directory: G:\PROJECT\exam-quiz\front-quiz\src\assets